### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [dchaplinsky/aiohttp_validate#299]
Can i use this project with `~=` operator? Does it follow [Semantic versioning](https://semver.org)?
 
```
aiohttp-validate~=1.1.0
```

**Comment by dchaplinsky** [comment]
Yes it does.

**Comment by alvassin** [comment]
Thank you very much. Could you please specify that it README to make it clear for others how to add it to requirements.txt?
